
  development:
    adapter: postgresql
    encoding: unicode
    database: sampleapp_dev
    pool: 5
    username: sampleapp
    password: popu1316
    min_messages: WARNING
  test:
    adapter: postgresql
    encoding: unicode
    database: sampleapp_test
    pool: 5
    username: sampleapp
    password: popu1316
    min_messages: WARNING
  production:
    adapter: postgresql
    database: sampleapp_live
    username: sampleapp
    password: popu1316
