
  development:
    adapter: postgresql
    encoding: unicode
    database: sampleapp_dev
    pool: 5
    username: sampleapp
    password: popu1316
    min_messages: WARNING
    host: localhost
    port: 5432
  test:
    adapter: postgresql
    encoding: unicode
    database: sampleapp_test
    pool: 5
    username: sampleapp
    password: popu1316
    min_messages: WARNING
    host: localhost
    port: 5432
  production:
    adapter: postgresql
    database: sampleapp_live
    username: sampleapp
    password: popu1316
    host: localhost
    port: 5432
